[build]
  publish = "public"  # Directory where built files will go
  command = "pip install -r requirements.txt && flask build && flask run --host=0.0.0.0 --port=$PORT"

[context.production.environment]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"